### ISSUE TITLE
endofproofwd is incorrectly packaged

### ISSUE THREAD

**Issue by SebastianPingu** [MiKTeX/miktex-packaging#176]
This pakage is incorrectly packaged, https://miktex.org/packages/endofproofwd.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by SebastianPingu** [comment]
Hello, it seems like it still doesn't work, at least for me. I don't get all files from Miktex and have to download them manually from ctan plus the `.pdf_tex` is not getting found by `pdflatex`.

Greetings and thank you

**Comment by edocevoli** [comment]
Sorry does it not work for you. For me it works:

```
kpsewhich endofproofwd.pdf_tex
```
returns `PATH_TO_MIKTEX_INSTALL_DIR/tex/latex/endofproofwd/endofproofwd.pdf_tex`
