### ISSUE TITLE
missing `.dfu` files from the hebrew-fonts package

### ISSUE THREAD

**Issue by Udi-Fogiel** [MiKTeX/miktex-packaging#398]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The files are produced from `hebinp.dtx` and called `lheenc.dfu`, `he8enc.dfu` and `nhe8enc.dfu`. 
All the other files are up to date ith ctan.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by Udi-Fogiel** [comment]
Thank you for addressing this. I updated the packages today and I still don't find the files any where, nor the package documentation.  

Reading `package-manifests.ini` it looks like these files should be in the doc folder of the package (which is missing), but then TeX will not be able to find them.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by Udi-Fogiel** [comment]
Everything is working now. Thanks!
