### ISSUE TITLE
Problem with package fontscripts

### ISSUE THREAD

**Issue by petiard** [MiKTeX/miktex-packaging#443]
Hello

In MiKTeX Console, Packages, the list of packages contains fontscripts but there is no file fontscripts.tar.lzma in MIKTeX repositories.
There are fontscripts__doc and fontscripts__source but not fontscripts.

Best regards

François

**Comment by petiard** [comment]
With the update today (27 october), the problem is still here.

François

**Comment by petiard** [comment]
Still the same problem...(26 November).
François

**Comment by iperlinuxiano** [comment]
Same here (4 December). Months without an answer...

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by petiard** [comment]
Hello
Sorry but the problem is still here.
fontscripts_doc has been updated, fontscripts_source has been deleted, but fontscripts doesn't exist but is in the list of packages !
![fontscripts_problem](https://github.com/user-attachments/assets/98914aa8-c4e4-41ca-b2de-1a4b69ea2712)

François
